services:
  worker:
    build: .
    env_file: .env.example
    environment:
      AUTOSTREAM_NODE_CONFIG: /etc/autostream-node/config.yml
    ports:
      - "8080:8080"
    volumes:
      - ./config/autostream-node.yml:/etc/autostream-node/config.yml:ro
